#!/bin/bash
#
# 1Password CLI command helper.
#
# MIT License
#
# Copyright (c) 2018 Harvey Thompson
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
_1PASS_OP=${_1PASS_OP:-op}
_1PASS_JQ=${_1PASS_JQ:-jq}
_1PASS_VERBOSE=${_1PASS_VERSION:-false}
_1PASS_INPUT=${_1PASS_INPUT:-gui}
_1PASS_ASKPASS=${_1PASS_ASKPASS:-${SSH_ASKPASS:-ssh-askpass}}
_1PASS_CONFIG=${_1PASS_CONFIG:-$HOME/.op/config}
_1PASS_MASTER_PASSWORD=${_1PASS_MASTER_PASSWORD:-}

function usage()
{
    echo "usage: 1pass ...

Simple frontend 1Password information using 'op' 1Password CLI command.

-p title	Print the password for the given entry with 'title'.
-u title	Print the username for the given entry with 'title'.
-U title	Print the URL for the given entry with 'title'.
-s regexp	Print any titles which match the case-insensitive extended RE 'regexp'.
-l, --list	List all available titles.

-v, --verbose	Verbose output to stderr.

-t, --terminal	Force use of TTY terminal for any password input.
-g, --gui	Force use of GUI for any password input.

--login		Ensure session is logged in. Must evaluate in shell (eg. 'eval \$(1pass --login)')
--logout	Ensure session is logged out. Must evaluate in shell (eg. 'eval \$(1pass --logout)')
--login-valid	Exit status 0 if session is valid, or non-zero if not.
" >&2
    exit 1
}

# --------------------------------------------------------------------------------
# Helpers
#

function error()
{
    echo "Error: 1pass: $*" >&2
    exit 1
}

function verb()
{
    [[ "$_1PASS_VERBOSE" != "true" ]] && return
    echo "1pass: $*" >&2
}

function eval_variable()
{
    local var="$1"
    eval echo \"\$"$var"\"
}

# --------------------------------------------------------------------------------
# 1Password query
#

function op_validate_query()
{
    local op_key="$1" op_field="$2" op_status="$3" op_value="$4"
    if [[ "$op_value" == "" || $op_status -ne 0 ]]; then
	error "cannot get $op_field for $op_key"
    fi
    echo "$op_value"
}

function get_op_item_field()
{
    local item_key="$1"
    local item_field_type="$2"
    local item_field="$3"
    local op_value="$($_1PASS_OP get item "$item_key" 2>/dev/null | $_1PASS_JQ -r '.details.fields[] | select(.'"$item_field_type"'=="'"$item_field"'").value' 2>/dev/null)"
    local op_status=${PIPESTATUS[0]}
    op_validate_query "$item_key" "$item_field" "$op_status" "$op_value"
}

function get_op_item_overview()
{
    local item_key="$1"
    local item_field="$2"
    local op_value="$($_1PASS_OP get item "$item_key" 2>/dev/null | $_1PASS_JQ -r '.overview.'"$item_field" 2>/dev/null)"
    local op_status=${PIPESTATUS[0]}
    op_validate_query "$item_key" "$item_field" "$op_status" "$op_value"
}

function get_op_item_username()
{
    local item_key="$1"
    get_op_item_field "$item_key" "designation" "username"
}

function get_op_item_password()
{
    local item_key="$1"
    get_op_item_field "$item_key" "designation" "password"
}

function get_op_item_url()
{
    local item_key="$1"
    get_op_item_overview "$item_key" "url"
}

function list_op_items()
{
    $_1PASS_OP list items 2>/dev/null | $_1PASS_JQ -r '.[] | select(.templateUuid == "001").overview.title' | sort
    local op_status=${PIPESTATUS[0]}
    if [[ $op_status -ne 0 ]]; then
	error "cannot get list of 1Password items"
    fi
}

function search_op_items()
{
    local search="$1"
    list_op_items | egrep -i "$search"
    local op_status=${PIPESTATUS[0]}
    if [[ $op_status -ne 0 ]]; then
	exit $op_status
    fi
}

# --------------------------------------------------------------------------------
# 1Password login/logout
#


function read_password_terminal()
{
    local prompt="$1"
    local pass=""

    if [[ "$TERM" == "dumb" ]]; then
	read -p "$prompt: " pass
    else
	read -s -p "$prompt: " pass
	echo "" >&2
    fi
    echo "$pass"
}

function read_password_gui()
{
    SSH_ASKPASS_TITLE="1Password" "$_1PASS_ASKPASS" "$prompt"
}

function read_password()
{
    local prompt="$1"
    local var="$2"

    while true
    do
	local var_value="$(eval_variable $var)"
	[[ "$var_value" != "" ]] && break

	eval $var=\""$(read_password_$_1PASS_INPUT "$prompt")"\"
    done
    echo "export $var=\"$(eval_variable $var)\""
}

function op_latest_signin()
{
    if [[ ! -f $_1PASS_CONFIG ]]; then
	return
    fi
    $_1PASS_JQ -r '.latest_signin' < $_1PASS_CONFIG
}

function op_config_value()
{
    local field="$1"
    if [[ ! -f $_1PASS_CONFIG ]]; then
	error "no existing op configuration found in $_1PASS_CONFIG"
    fi
    local latest_signin="$()"
    $_1PASS_JQ -r '.accounts[] | select(.shorthand == "'"$latest_signin"'").'"$field"'' < $_1PASS_CONFIG
}

function op_login()
{
    # TODO: if no current op config or latest signin, ask for all information required for full login
    
    local email="$(op_config_value email)"
    local prompt="Master password for $email"

    read_password "$prompt" _1PASS_MASTER_PASSWORD

    # TODO: try to sign in
    # check if signed in
    # repeat until succesful...
}

function op_logout()
{
    if $_1PASS_OP signout 2>/dev/null
    then
	verb "Session logged out."
	local latest_signin="$(op_latest_signin)"
	if [[ "$latest_signin" != "" ]]; then
	    echo "unset OP_SESSION_${latest_signin}"
	    verb "Session environment cleared."	    
	fi
    else
	verb "Session already logged out."
    fi
}

function op_login_valid()
{
    local latest_signin="$(op_latest_signin)"
    if [[ "$latest_signin" == "" ]]; then
	verb "No op config or latest signin, must not be logged in."
	exit 1
    fi

    local session="$(eval_variable OP_SESSION_${latest_signin})"
    if [[ "$session" == "" ]]; then
	verb "No session key, must not be logged in."
	exit 1
    fi

    $_1PASS_OP list users >/dev/null 2>&1
    local op_status=$?
    if [[ $op_status -ne 0 ]]; then
	verb "Session key timed out or invalid."
	exit 1
    else
	verb "Session key valid and logged in."
	exit 0
    fi
}

short_opts="p:u:U:s:lvtg"

function process_opt()
{
    local opt="$1"

    case "$opt" in
	p)
	    get_op_item_password "$OPTARG"
	    ;;
	u)
	    get_op_item_username "$OPTARG"
	    ;;
	U)
	    get_op_item_url "$OPTARG"
	    ;;
	s)
	    search_op_items "$OPTARG"
	    ;;
	l|list)
	    list_op_items
	    ;;
	v|verbose)
	    _1PASS_VERBOSE=true
	    ;;
	t|terminal)
	    _1PASS_INPUT=terminal
	    ;;
	g|gui)
	    _1PASS_INPUT=gui
	    ;;
	login)
	    op_login
	    ;;
	logout)
	    op_logout
	    ;;
	login-valid)
	    op_login_valid
	    ;;
	*)
	    usage
	    ;;
    esac
}

# --------------------------------------------------------------------------------
# Main

while getopts "${short_opts}-:" c
do
    case "$c" in
	-)
	    long_opt="$OPTARG"
	    OPTARG=""
	    process_opt "$long_opt"
	    ;;
	*)
	    process_opt "$c"
	    ;;
    esac
done
shift $((OPTIND - 1))
if [[ $# -ne 0 ]]; then
    usage
fi
exit 0

